launchbox:
  enabled: true
  downloadUrl: "https://gamesdb.launchbox-app.com/Metadata.zip"
  # xmlPath: "/path/to/launchbox.xml"
igdb:
  enabled: true
  clientId: "your_client_id"
  clientSecret: "your_client_secret"